_format_version: "2.1"

services:
  - name: auth
    url: http://supabase-auth:9999
    routes:
      - name: auth
        paths:
          - /auth/v1/

  - name: rest
    url: http://supabase-rest:3000
    routes:
      - name: rest
        paths:
          - /rest/v1/
